index:
    path: /
    controller: App\Controller\TechNews\IndexController::index

accueil:
  path: /accueil
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: index
    permanent: true # code http qui change en fonction de true or false

mentions_legales:
    path:         /mentions-legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentionslegales.html.twig

deconnexion:
    path: /deconnexion